### ISSUE TITLE
Week 19-20 Worklog

### ISSUE THREAD

**Issue by wdhub** [wdhub/jsPsych#8]
- [x] Finialize title generation based on similarity table:

- modify instructions
- redirect to prolific at the end
- clean the console

- [x] Store data in csv via Python.

- [x] Solve the API key security issue

- [x] Document the program and help with implementation
- Frontend
  - how to change experiment settings: conditions(incl URL), assets, title&version
  - how adjust current pages: div, js and css
  - how to add new pages: views, plugin npm, import/export
  - how to locally test: console (remember to comment) and elements
- API
  - how to modify the task/settings of API
  - how to encrypt the key and forbid F12
- Backend
  - how different data is initialized and saved from different models and how to adjust it
  - How to parse the results via python
  - how to manage experiments and data in Jatos

  - how to use python libraries and functions from Js: install, set up, codes, init and usage in Js, limitation

- Update the document menu and function comments.

**Comment by wdhub** [comment]
modified instructions
cleaned the console
redirecting to prolific at the end:
- use window.location in the last slide->works for local, but not Jatos; Jatos reported "Batch channel closed"->[Jatos solution](https://www.jatos.org/Tips-and-Tricks.html) is to allow HTTPS in the server,seems [a bit complex](https://www.digitalocean.com/community/questions/how-do-i-force-https-for-a-droplet)
- use window.open to open new page->local not allowed new page, Jatos reported "Won't open batch channel because study is about to move to the next component or finish."->open it ealier?
- want to use [jatos.endStudyAndRedirect](https://www.jatos.org/jatos.js-Reference.html#jatosendstudyandredirect) but without the access to jatos library outside the [app.js](https://github.com/bjoluc/jspsych-builder/blob/77461abe905fd7f2743bb96c77f0eadfb9dc765b/assets/app.js#L10) which is created during packaging. [Possible method here](https://github.com/bjoluc/jspsych-builder/issues/38)
- add endPage.html in assets and jump to Prolific with it....

**Comment by huisunsh** [comment]
there is a JATOS documentation page on integration with Prolific: https://www.jatos.org/Use-Prolific.html. This may help?

**Comment by wdhub** [comment]
> there is a JATOS documentation page on integration with Prolific: https://www.jatos.org/Use-Prolific.html. This may help?

That's the methods I'm trying above. I will continue exploring a bit, otherwise we can:
provide a link in the webpage for user to manually jump to Prolific.

**Comment by wdhub** [comment]
Fixed redirection issue via using jatos library in Jatos server.
Clearified the data storage via controlling the data sent to Jatos.
`    jsPsych = initJsPsych({
        on_finish: () => {
            if (typeof jatos !== 'undefined') {
                // in jatos environment
                jatos.endStudyAndRedirect(`https://app.prolific.com/submissions/complete?cc=${user_batch}`, JSON.stringify(jsPsych.data.get().select('myResult')));
            } else {
                return jsPsych;
            };
        }
    });`

**4 hours of work.**

**Comment by wdhub** [comment]
Trying to solve the api key leak via base64 encoding/decoding

**2 hours of work**

**Comment by wdhub** [comment]
Implemented data parsing via Python, output:
- titles: chosen,all presented, own
- user feedback: ratings,comment, score
- condition: user batch, similarity, distracted, similarity table+show score+slider, attention
- user info: age, gender, ID

**Comment by wdhub** [comment]
Implemented data parsing via Python, output:
- titles: chosen,all presented, own
- user feedback: ratings,comment, score
- condition: user batch, similarity, distracted, similarity table+show score+slider, attention
- user info: age, gender, ID

**3 hours of work.**

**Comment by wdhub** [comment]
# Perception experiment
A JsPsych website for psychology experiment. During the experiment, openAI API will be called multiple times to generate the stimuli. The website is interactive, i.e the displayed content may change according to participants' choices. Sequentially, the participants would be shown with the introductions, interaction pages, surveys and an ending page.

This readme will explain how to install and use the program, as well as the design principles. For the design process, please refer to [issues](https://github.com/wdhub/jsPsych/issues).

For research purpose, the project is led by [Hui Sun](https://www.huisunsh.com/) from House of Innovation, Stockholm School of Economics. See paper (not published yet)...
Contact: [Yawen](yawend@kth.se), research assistant, if you have any question.

## Update:
In the latest release, the experiment allows participants to come up with a painting title collaborating with the AI. After reading the instructions, they have the choice to accept the generated title or to generate a new one, as well as controlling the similarity of the coming title via a slider. Once a title is picked, participant could optionally propose their own titles. In the following survey, user validation on the interaction and some additional information are required. Finally, participants would be directed to a Prolific page for their rewards, etc.

Here is a link to try it out:[demo at Jatos](http://157.230.27.41/publix/6jq04deNr3b)

Here is a screen record of how it works.


## Tech Stack:
The website is built around the [Jspsych](https://www.jspsych.org/7.3/) framework. The reason why we adopt this framework rather than React or VueX is that it provides ready-to-use process control plugins for behavioral experiments. Such as the timeline that navigates throughout the experiment, reaction time recorder, eye-tracker, etc. Besides the framework, [jsPsych Builder](https://github.com/bjoluc/jspsych-builder), a React ClI, is ultilized to set up and update the environment. With the simple commands like "npm run build" or "npm run jatos", the program could be packaged.

[Jatos](https://www.jatos.org/) is used to manage experiment results. The reason why Jatos is preferred than Firebase is the built-in access control. For instance, researchers can choose in the panel the participant's access level of the shared URL link. Some could be submitted multiple times, some could be submitted only once in the same IP. 

To host the webiste remotely, a server in German with Docker on Ubuntu pre-installed is picked from [DigitalOcean](https://www.digitalocean.com/). The location is selected due to performance requirement and academic ethics. 

OpenAI API is maily called to generate the stimuli. In specific, [gpt-3.5-turbo-0125](https://platform.openai.com/docs/guides/text-generation/completions-api) is the currently used model, with the purpose of text generation. Each fetch of the API may take around 1 second, depending on the current load of openAI platform and the local network of the participant. Therefore, a loading feature is needed in the UI.

![图片1](https://github.com/wdhub/jsPsych/assets/56460190/691771bd-d73e-412b-bc14-aaf96f5b416e)

## Get Started
- Before you get started: 
	- make sure you have git bash/github desktop and `npm` installed in your computer
	- In need of hosting the webiste remote, there should be a server with Jatos installed. 
	- In need of parsing the results via the python codes, a python IDE, e.g PyCharm, might need to be used.
	- recommended version: `Node.js>=18`, browser `Firefox>=112`, as required by Pyodide.
- Download the repository under your chosen directory via
```
git clone https://github.com/wdhub/jsPsych.git
```

- Configuration: 
	- Load the plugin that enables webpack knowing the environment variables. Open the CMD under the directory and enter this line. 
	```
	npm i webpack-define-envs-plugin
	```	
	- Encrypted your openai key.In this program, base64 encryption is used. However, we recommend you to use more complex methods and then modify the decoding function in `API/openAI,js` accordingly.
	
	- Add the encrypted key as a system environment variable via the advanced setting in your PC. This is adviced by openAI for [security reasons](https://help.openai.com/en/articles/5112595-best-practices-for-api-key-safety).
	```
	Variable name:OPENAI_API_KEY
	Variable value:<your_encrypted_key>

	```

- Run the website locally: open the CMD under the directory and enter this line. It might take some minutes in the first time. 
```
npm start
```
Enter `localhost:3000` in your browser as the npm indicates project running. If the website is able to interact as the demo, the environment are set up successfully.

- Run the experiment remotely: Package the experiment via
```
npm run jatos
```
The packaged `.jzip` file will be found in the `/packaged`. Then import it in your remote Jatos server and run. If it runs as local, congratulations! The project is installed in your cloud server.

- Parse results: create a `/result` folder in the root and put txt experiment result inside, if you want to use the python file to parse results.The parsed result will be saved as CSV file in the same `/result` folder.

## Programming Guide
You are welcome to customize your own experiment on this project. Here I will explain the design of the architecture a bit, so that it's easier to follow. Instead of the full MVP model, we use a simplified version, consisting only of views and models. 

The views only care about UI and pass the data to models by calling the methods from models. Such as `setResult()` and `getHaiku_API()`. Given the nature of experiments, 3 kinds of views are designed, focusing on introducing the experiment, interacting with the participants with actual stimulis and showing the result respectively. Each view may have multiple slides, depending on the experiment. Yet we try to keep the structure clean, with intro view merely displaying instructions and end view merely indicating the end of the experiment. The rest of the API fetch and so on should be in the stimuli view. In the future, there might be a personal-data view and a try-out view, if required in the experiment. Models are the ones which actually process and store the data, and handling API requests. As for updating the data to Jatos, this is currently handled by jspsych-builder automatically.

### Useful Links
- [Plugins in Jspsych](https://www.jspsych.org/7.3/plugins/list-of-plugins/)
- [How to set up a new experiment via jsPsych Builder](https://github.com/bjoluc/jspsych-builder)
- [Step-by-step install Jatos in DigitalOcean](https://www.jatos.org/next/JATOS-on-DigitalOcean.html)
- [Examples of experiments using Jatos (Jspsych, React, etc)](https://www.jatos.org/Example-Studies.html)

### File Structure
- views/
	- introView.js: the introduction page display, jump to stimuli page or end page
	- stimuliView.js: display the stimuli, jump to the same page under certain condition or to the end page
	- endView.js: display the results

- models/
	- resultModel.js:contain the global data related to API fetch results, user reactions
	- jsPsychModel.js:manage the jsPsych object

- APIs/
	- openAI.js:init and call openAI for various purposes

- utilities.js:repetitively used functions
- experiment.js: initialize and mount the exp

**Comment by wdhub** [comment]
# Perception experiment
A JsPsych website for psychology experiment. During the experiment, openAI API will be called multiple times to generate the stimuli. The website is interactive, i.e the displayed content may change according to participants' choices. Sequentially, the participants would be shown with the introductions, interaction pages, surveys and an ending page.

This readme will explain how to install and use the program, as well as the design principles. For the design process, please refer to [issues](https://github.com/wdhub/jsPsych/issues).

For research purpose, the project is led by [Hui Sun](https://www.huisunsh.com/) from House of Innovation, Stockholm School of Economics. See paper (not published yet)...
Contact: [Yawen](yawend@kth.se), research assistant, if you have any question.

## Features:
- Intergrated with `openAI API`
- Basic level of security for keys and user data
- Customized `Jspysch-based` components
- Customized Python algorithm for parsing experiment result into `.csv`
- User guidance, preventing participants missing or misunderstanding any question
- Easy launching via `Jatos`


## Update:
In the latest release, the experiment allows participants to come up with a painting title collaborating with the AI. After reading the instructions, they have the choice to accept the generated title or to generate a new one, as well as controlling the similarity of the coming title via a slider. Once a title is picked, participant could optionally propose their own titles. In the following survey, user validation on the interaction and some additional information are required. Finally, participants would be directed to a Prolific page for their rewards, etc.

Here is a link to try it out:[demo at Jatos](http://157.230.27.41/publix/6jq04deNr3b)

If the link no long works, this is a screen record of how it works.
![demo](https://github.com/wdhub/jsPsych/assets/56460190/e30b7e45-11cf-420f-9f9d-21fc3414f0c1)

## Tech Stack:
The website is built around the [Jspsych](https://www.jspsych.org/7.3/) framework. The reason why we adopt this framework rather than React or VueX is that it provides ready-to-use process control plugins for behavioral experiments. Such as the timeline that navigates throughout the experiment, reaction time recorder, eye-tracker, etc. Besides the framework, [jsPsych Builder](https://github.com/bjoluc/jspsych-builder), a React ClI, is ultilized to set up and update the environment. With the simple commands like "npm run build" or "npm run jatos", the program could be packaged.

[Jatos](https://www.jatos.org/) is used to manage experiment results. The reason why Jatos is preferred than Firebase is the built-in access control. For instance, researchers can choose in the panel the participant's access level of the shared URL link. Some could be submitted multiple times, some could be submitted only once in the same IP. 

To host the webiste remotely, a server in German with Docker on Ubuntu pre-installed is picked from [DigitalOcean](https://www.digitalocean.com/). The location is selected due to performance requirement and academic ethics. 

OpenAI API is maily called to generate the stimuli. In specific, [gpt-3.5-turbo-0125](https://platform.openai.com/docs/guides/text-generation/completions-api) is the currently used model, with the purpose of text generation. Each fetch of the API may take around 1 second, depending on the current load of openAI platform and the local network of the participant. Therefore, a loading feature is needed in the UI.

![图片1](https://github.com/wdhub/jsPsych/assets/56460190/691771bd-d73e-412b-bc14-aaf96f5b416e)

## Get Started
- Before you get started: 
	- make sure you have git bash/github desktop and `npm` installed in your computer
	- In need of hosting the webiste remote, there should be a server with Jatos installed. 
	- In need of parsing the results via the python codes, a python IDE, e.g PyCharm, might need to be used.
	- recommended version: `Node.js>=18`, browser `Firefox>=112`, as required by Pyodide.
- Download the repository under your chosen directory via
```
git clone https://github.com/wdhub/jsPsych.git
```

- Configuration: 
	- Load the plugin that enables webpack knowing the environment variables. Open the CMD under the directory and enter this line. 
	```
	npm i webpack-define-envs-plugin
	```	
	- Encrypted your openai key.In this program, base64 encryption is used. However, we recommend you to use more complex methods and then modify the decoding function in `API/openAI,js` accordingly.
	
	- Add the encrypted key as a system environment variable via the advanced setting in your PC. This is adviced by openAI for [security reasons](https://help.openai.com/en/articles/5112595-best-practices-for-api-key-safety).
	```
	Variable name:OPENAI_API_KEY
	Variable value:<your_encrypted_key>

	```

- Run the website locally: open the CMD under the directory and enter this line. It might take some minutes in the first time. 
```
npm start
```
Enter `localhost:3000` in your browser as the npm indicates project running. If the website is able to interact as the demo, the environment are set up successfully.

- Run the experiment remotely: Package the experiment via
```
npm run jatos
```
The packaged `.jzip` file will be found in the `/packaged`. Then import it in your remote Jatos server and run. If it runs as local, congratulations! The project is installed in your cloud server.

- Parse results: create a `/result` folder in the root and put txt experiment result inside, if you want to use the python file to parse results.The parsed result will be saved as CSV file in the same `/result` folder.

## Programming Guide
You are welcome to customize your own experiment on this project. Here I will explain the design of the architecture a bit, so that it's easier to follow. Instead of the full MVP model, we use a simplified version, consisting only of views and models. 

The views only care about UI and pass the data to models by calling the methods from models. Such as `setResult()` and `getHaiku_API()`. Given the nature of experiments, 3 kinds of views are designed, focusing on introducing the experiment, interacting with the participants with actual stimulis and showing the result respectively. Each view may have multiple slides, depending on the experiment. Yet we try to keep the structure clean, with intro view merely displaying instructions and end view merely indicating the end of the experiment. The rest of the API fetch and so on should be in the stimuli view. In the future, there might be a personal-data view and a try-out view, if required in the experiment. Models are the ones which actually process and store the data, and handling API requests. As for updating the data to Jatos, this is currently handled by jspsych-builder automatically.

### Useful Links
- [Plugins in Jspsych](https://www.jspsych.org/7.3/plugins/list-of-plugins/)
- [How to set up a new experiment via jsPsych Builder](https://github.com/bjoluc/jspsych-builder)
- [Step-by-step install Jatos in DigitalOcean](https://www.jatos.org/next/JATOS-on-DigitalOcean.html)
- [Examples of experiments using Jatos (Jspsych, React, etc)](https://www.jatos.org/Example-Studies.html)

### File Structure
- views/
	- introView.js: the introduction page display, jump to stimuli page or end page
	- stimuliView.js: display the stimuli, jump to the same page under certain condition or to the end page
	- endView.js: display the results

- models/
	- resultModel.js:contain the global data related to API fetch results, user reactions
	- jsPsychModel.js:manage the jsPsych object

- APIs/
	- openAI.js:init and call openAI for various purposes

- utilities.js:repetitively used functions
- experiment.js: initialize and mount the exp

**Comment by wdhub** [comment]
Fixed the new slider.
Finished documentation.

**9 hours of work.**

**Comment by wdhub** [comment]
Fine tuned the mapping between slider similarity and openAI API temperature;
Sorted the codes and improve readability.

**3 hours of work.**
